# Generated by Django 4.1.1 on 2022-09-16 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category_product_end_date_product_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='crated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
